### ISSUE TITLE
SAC for Procgen/other discrete action spaces?

### ISSUE THREAD

**Issue by nhansendev** [KarlXing/RLCodebase#15]
I was curious about the performance of SAC on Procgen using your implementation, but I am having difficulty configuring it for the Discrete action space. Would you consider adding Discrete support in the trainer as well (if it's not already there)?

**Comment by KarlXing** [comment]
Hi, I think discrete-SAC is not there yet. I will add it to my to-do list but I have some other tasks with higher priorities on the list and thus cannot guarantee anything about the implementation of discrete-SAC for now.
